config/routes.rb
Rails.application.routes.draw do
  # API
  mount API::Base=> '/'

  # User
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/authentications"
  }

  namespace :users, as: :user do
    namespace :authentications, as: :authentication, path: :auth do
      delete "/:provider" => :destroy
    end

    get "/:name" => :show
  end

  # Photo
  resources :photos

  # Root
  authenticated :user do
    root "photos#new", as: :authenticated_root
  end

  unauthenticated do
    root "static_pages#index", as: :unauthenticated_root
  end

  # Error
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404', via: [:get, :post]
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  # include Colourable
  include Tokenable

  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  before_create :set_salt

  def set_salt
    self.salt = Digest::SHA1.hexdigest("#{rand(999)}.#{rand(999)}.#{image.filename}.#{image.content_type}")
  end

  def expirable?
    expired_at.present?
  end

  # Return true if photo has been expired
  def expired?
    if expirable?
      expired_at < Time.now
    else
      false
    end
  end

  def view!
    self.view_count += 1
    save
  end
end

app/controllers/api/v1/photos.rb
class API::V1::Photos < Grape::API
  resource :photos do
    # GET /api/v1/photos/:id
    get ":id", rabl: 'photo' do
      @photo = Photo.find(params[:id])
    end

    # POST /api/v1/photos
    post '/', rabl: 'photo' do
      @photo = current_user.photos.build(photo_params)
      @photo.image = ActionDispatch::Http::UploadedFile.new(params[:photo]) if params[:photo]
      @photo.save!
      @photo.reload
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, except: %i(show)
  before_action :set_photo, only: %i(show edit update destroy)

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  def index
    @photos = policy_scope(current_user.photos)

    @photos.each do |photo|
      photo.destroy if photo.expired?
    end
  end

  def show
    authorize @photo

    @photo.destroy if @photo.expired?
    @photo.view!
  end

  def new
    @photo = Photo.new
    authorize @photo
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id

    authorize @photo

    if @photo.save
      redirect_to @photo
    else
      render :new
    end
  end

  def edit
    authorize @photo
  end

  def update
    authorize @photo

    if @photo.update_attributes!(photo_params)
      redirect_to @photo
    else
      render :edit
    end
  end

  def destroy
    authorize @photo

    if @photo.destroy
      redirect_to photos_path
    else
      render :edit
    end
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:image, :expired_at)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper

end

app/views/photos/_error_explanation.html.slim
- if record.errors.any?
  #error_explanation
    h2 = "#{pluralize(record.errors.count, "error")} prohibited this photo from being saved:"
    ul
      - record.errors.full_messages.each do |message|
        li = message

app/views/photos/_form.html.slim
= form_for @photo, html: { multipart: true } do |f|
  == render 'error_explanation', { record: @photo }

  .input-group.image-drop-zone
    = f.file_field :image

  = f.hidden_field :expired_at
  .input-group
    .range-slider
      label.range-slider-label 1h
      .range-slider-ui
  .input-group
    .datetimepicker style='display: none'
      .input-group.date
        input.form-control.datepicker type='text' placeholder='日付'
      .input-group.time
        input.form-control.timepicker type='text' placeholder='時間'

    coffee:
      secondsToTime = (secs)->
        hours = Math.floor(secs / (60 * 60))

        divisor_for_minutes = secs % (60 * 60)
        minutes = Math.floor(divisor_for_minutes / 60)

        divisor_for_seconds = divisor_for_minutes % 60
        seconds = Math.ceil(divisor_for_seconds)

        texts = []
        if hours then texts.push "#{hours}h"
        if minutes then texts.push "#{minutes}m"
        if seconds then texts.push "#{seconds}s"

        return if texts.length > 0 then texts.join(' ') else "0"

      $ ->
        $('.range-slider-ui').noUiSlider({
          start: 60,
          step: 5,
          range: {
            min: 0,
            max: 360
          }
        })

        $('.range-slider-ui').on 'slide', ->
          at = parseInt($(this).val())*60
          if at == 0
            $(this).parent().find(".range-slider-label").text('Limitless')
            $('#photo_expired_at').val ''
          else
            $(this).parent().find(".range-slider-label").text(secondsToTime(at))
            $('#photo_expired_at').val moment().add('seconds', at).format()

        $('.datepicker').pickadate({
          format: 'yyyy-mm-dd',
          min: new Date()
        })

        $('.timepicker').pickatime({
          format: 'HH:i',
          interval: 5
        })

        $('.datepicker, .timepicker').on 'change', ->
          $('#photo_expired_at').val("#{$('.datepicker').val()} #{$('.timepicker').val()}")

        # $('.timepicker').val($('#photo_expired_at').val().split(' ')[0])

        picker_type = 'slider'
        $('#js-toggle-picker').on 'click', (e)->
          e.preventDefault()
          if picker_type == 'slider'
            $(this).find('.button-icon').removeClass('fa-calendar-o').addClass('fa-clock-o')
            $('.range-slider').hide()
            $('.datetimepicker').show()
            picker_type = 'date'
          else
            $(this).find('.button-icon').removeClass('fa-clock-o').addClass('fa-calendar-o')
            $('.datetimepicker').hide()
            $('.range-slider').show()
            picker_type = 'slider'

        at = parseInt($('.range-slider-ui').val())*60
        $('#photo_expired_at').val moment().add('seconds', at).format()

  .actions
    .button-group
      = f.submit 'Upload', class: 'button button-green'
      button#js-toggle-picker.button.button-darkgreen
        i.button-icon.fa.fa-calendar-o

app/views/photos/edit.html.slim
.wrapper
  .layout
    h2 Editing Photo
    .group.columns
      figure.column
        = link_to @photo do
          = image_tag @photo.image.thumb.url
          figcaption.column-caption
            ul.horizontal.column-caption-labels
              li title='View Count'
                i.icon.fa.fa-eye
                = @photo.view_count
              - if @photo.expired_at.present?
                li title='Expired At'
                  i.icon.fa.fa-clock-o
                  = distance_of_time_in_words(Time.now, @photo.expired_at)
      figure.column
        .inner
          h2 Update
          == render 'form'
          = link_to photo_path(@photo), method: :delete, confirm: 'Are you sure?', class: 'button button-red' do
            i.fa.fa-trash-o

app/views/photos/index.html.slim
.wrapper
  .layout
    h2 Manage Photos
    - if @photos.blank?
      .group
        h1 Add your some images here!
    .group.columns.photos
      - @photos.each do |photo|
        - if photo.destroyed?
          figure.column
            = image_tag 'icon-404.png'
        - else
          figure.column
            = link_to photo do
              = image_tag photo.image.thumb.url
            figcaption.column-caption
              ul.horizontal.column-caption-labels
                li title='View Count'
                  i.icon.fa.fa-eye
                  = photo.view_count
                - if photo.expired_at.present?
                  li title='Expired At'
                    i.icon.fa.fa-clock-o
                    = distance_of_time_in_words(Time.now, photo.expired_at)
              ul.horizontal.column-caption-controls
                - if photo.user == current_user
                  li = link_to '編集', edit_photo_path(photo)

app/views/photos/new.html.slim
- content_for :header_icon_color, 'white'

.wrapper.landscape
  .box.photo-form
    h2 Upload Photo
    == render 'form'

app/views/photos/show.html.slim
- content_for(:meta_tag) do
  meta name="twitter:card" content="photo"
  meta name="twitter:image:src" content=@photo.image_url(:medium)
  meta name="twitter:domain" content=photo_url(@photo)

- content_for(:header) do
  = link_to '', user_root_path,
    class: 'logo icon-torapic-logo-square',
    id: 'js-sidebar-toggle',
    data: {color: :gray}
  ul.photo-info-list
    li.photo-info-item title='View Count'
      i.icon.fa.fa-eye
      = @photo.view_count
    li.photo-info-item title='Expired At'
      i.icon.fa.fa-clock-o
      - if @photo.expirable?
        = distance_of_time_in_words(Time.now, @photo.expired_at)
      - else
        span 無期限

- content_for(:sidebar_content) do
  ul.sidebar-list
    li.sidebar-list-item
      = link_to @photo.user do
        = gravatar_image_tag @photo.user.email, class: 'sidebar-list-item-icon'
        = @photo.user.name

.wrapper
  .photo
    = image_tag @photo.image_url(:medium), class: "photo-image",
      data: {original: @photo.image_url, medium: @photo.image_url(:medium)}