config/routes.rb
Rails.application.routes.draw do
  # API
  mount API::Base=> '/'

  # User
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/authentications"
  }

  namespace :users, as: :user do
    namespace :authentications, as: :authentication, path: :auth do
      delete "/:provider" => :destroy
    end

    get "/:name" => :show
  end

  # Photo
  resources :photos

  # Root
  authenticated :user do
    root "photos#new", as: :authenticated_root
  end

  unauthenticated do
    root "static_pages#index", as: :unauthenticated_root
  end

  # Error
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404', via: [:get, :post]
  end
end

app/views/layouts/_devise_messages.slim
- if notice || alert
  .flash-message class="#{notice ? "notice" : ""} #{alert ? "error" : ""}"
    .flash-text
      - if notice
        p = notice
      - elsif alert
        p = alert
    a.flash-close href="#" ×

  coffee:
    $ ->
      $('.flash-close').on "click", (e)->
        e.preventDefault()
        $(this).parent().hide()

app/views/layouts/_flash_message.slim
- if notice || alert
  .flash-message class="#{notice ? "notice" : ""} #{alert ? "error" : ""}"
    .flash-text
      - if notice
        p = notice
      - elsif alert
        p = alert

app/views/layouts/_header.html.slim
header.header
  .logo
  nav
    ul.horizontal
      li
        - if user_signed_in?
          = link_to 'Sign out', user_destroy_session_path, method: :delete
        - else
          = link_to 'Sign in', new_user_registration_path

app/views/layouts/_top.html.erb
<div class="layout-top">
  <header>

  </header>
  <%= yield %>
</div>

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Torapic

    meta name="viewport" content="width=device-width, minimal-ui"
    = yield(:meta_tag)

    = stylesheet_link_tag "application", media: "all"

    = javascript_include_tag "//fast.fonts.net/jsapi/ae647d66-7237-4767-aaa6-a318929c5731.js"
    = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"
    = javascript_include_tag :modernizr
    = javascript_include_tag :application

    = csrf_meta_tags
  body
    nav.sidebar
      .sidebar-header.visible
        - if content_for?(:header)
          = yield(:header)
        - else
          = link_to '', user_root_path,
            class: 'logo icon-torapic-logo-square',
            id: 'js-sidebar-toggle',
            data: { color: content_for?(:header_icon_color) ? yield(:header_icon_color) : 'gray' }

      .sidebar-scrollable-content
        ul.sidebar-list
          li.sidebar-list-item
            = link_to user_signed_in?? :authenticated_root : :unauthenticated_root do
              i.sidebar-list-item-icon.icon-torapic-logo
              | Home
          - if user_signed_in?
            li.sidebar-list-item
              = link_to photos_path do
                i.sidebar-list-item-icon.fa.fa-picture-o
                | Manage Photos
            li.sidebar-list-item
              = link_to edit_user_registration_path do
                i.sidebar-list-item-icon.fa.fa-gear
                | Settings
            li.sidebar-list-item
              = link_to destroy_user_session_path, method: :delete do
                i.sidebar-list-item-icon.fa.fa-sign-out
                | Sign out
          - else
            li.sidebar-list-item
              = link_to new_user_session_path do
                i.sidebar-list-item-icon.fa.fa-sign-in
                | Sign in
        = yield(:sidebar_content) if content_for?(:sidebar_content)
    .sidebar-overlay
    .scrollable-container
      .scrollable-region
        .scrollable-content
          == yield

    == render 'layouts/flash_message'